#!/usr/bin/env python

"""
Copyright 2013 YouView TV Ltd.
License: LGPL v2.1 or (at your option) any later version (see
https://github.com/drothlis/stb-tester/blob/master/LICENSE for details).
"""

import argparse
import sys

import stbt


parser = argparse.ArgumentParser()
parser.prog = "stbt config"
parser.description = """Prints the value of the specified key from the stbt
    configuration file. See 'configuration' in the stbt(1) man page."""
parser.epilog = \
    "Returns non-zero exit status if the specified key or section isn't found."
parser.add_argument(
    "section", nargs="?", default="global",
    help="""Look in the specified <section> of the config file,
        e.g. 'run' or 'record'
        (defaults to the 'global' section if <section> isn't specified)""")
parser.add_argument(
    "key", help="Configuration item to read")
args = parser.parse_args(sys.argv[1:])

print stbt.get_config(args.key, args.section)
