#!/usr/bin/env python

import sys
import traceback

import stbt


parser = stbt.argparser()
parser.prog = 'stbt run'
parser.description = 'Run an stb-tester test script'
parser.add_argument('script',
    help='The test script to run (default: %(default)s)')
parser.set_defaults(**stbt.load_defaults('run'))
args = parser.parse_args(sys.argv[1:])
stbt.debug("Arguments:\n" + "\n".join([
            "%s: %s" % (k, v) for k, v in args.__dict__.items()]))

stbt.init_run(args.source_pipeline, args.sink_pipeline, args.control)
from stbt import press, press_until_match, wait_for_match, wait_for_motion, \
    detect_match, MatchResult, Position, detect_motion, MotionResult, \
    save_frame, get_frame, \
    UITestError, UITestFailure, MatchTimeout, MotionTimeout, ConfigurationError
try:
    execfile(args.script)
except stbt.MatchTimeout as e:
    traceback.print_tb(sys.exc_traceback)
    print ("FAIL: %s: Didn't find match for '%s' after %d seconds." % (
        args.script, e.expected, e.timeout_secs))
    if e.screenshot:
        stbt.save_frame(e.screenshot, "screenshot.png")
        print ("Saved screenshot to '%s'." % ("screenshot.png"))
    sys.exit(1)
finally:
    stbt.teardown_run()
