#!/usr/bin/env python

import sys
import traceback

import stbt


parser = stbt.argparser()
parser.add_argument('script',
    help='The test script to run (default: %(default)s)')
args = parser.parse_args(sys.argv[1:])
stbt.debug("Arguments:\n" + "\n".join([
            "%s: %s" % (k, v) for k, v in args.__dict__.items()]))

stbt.init_run(args.source_pipeline, args.sink_pipeline, args.control)
from stbt import press, press_until_match, wait_for_match
try:
    execfile(args.script)
except stbt.MatchTimeout as e:
    stbt.save_frame(e.screenshot, "screenshot.png")
    traceback.print_tb(sys.exc_traceback)
    print ("FAIL: %s: Didn't find match for '%s' after %d seconds. " +
           "Saved screenshot to '%s'") % (
        args.script, e.expected, e.timeout_secs, "screenshot.png")
    sys.exit(1)
finally:
    stbt.teardown_run()
