#!/bin/sh

# Copyright 2014 stb-tester.com Ltd.
# License: LGPL v2.1 or (at your option) any later version (see
# https://github.com/stb-tester/stb-tester/blob/master/LICENSE for details).

#/ usage: stbt camera [--help] <command> [args]
#/
#/ Available commands are:
#/     calibrate      Configure stb-tester to use a camera pointing at a TV for
#/                    input
#/     validate       Measure the quality of camera input/calibration
#/
#/ For help on a specific command do 'stbt camera <command> --help'.
#/ See 'man stbt' for more detailed information.

this_dir=$(dirname "$0")
export PYTHONPATH="$this_dir:$PYTHONPATH"

usage() { grep '^#/' "$0" | cut -c4-; }

[ $# -ge 1 ] || { usage >&2; exit 1; }
cmd=$1
shift
case "$cmd" in
    -h|--help)
        usage; exit 0;;
    calibrate)
        exec "$this_dir"/stbt-camera.d/stbt-camera-calibrate.py "$@";;
    validate)
        exec "$this_dir"/stbt-run "$this_dir"/stbt-camera.d/stbt-camera-validate.py "$@";;
    *)
        usage >&2; exit 1;;
esac
