#!/usr/bin/env python
# coding=utf-8
"""
This file contains regression tests automatically generated by
``stbt auto-selftest``. These tests are intended to capture the
behaviour of Frame Objects (and other helper functions that operate on
a video-frame). Commit this file to git, re-run ``stbt auto-selftest``
whenever you make a change to your Frame Objects, and use ``git diff``
to see how your changes affect the behaviour of the Frame Object.

NOTE: THE OUTPUT OF THE DOCTESTS BELOW IS NOT NECESSARILY "CORRECT" --
it merely documents the behaviour at the time that
``stbt auto-selftest`` was run.
"""
# pylint: disable=line-too-long

import os
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(__file__), '../../../tests'))

from unicode_example import *  # isort:skip pylint: disable=wildcard-import, import-error

_FRAME_CACHE = {}


def f(name):
    img = _FRAME_CACHE.get(name)
    if img is None:
        import cv2
        filename = os.path.join(os.path.dirname(__file__),
                                '../../screenshots', name)
        img = cv2.imread(filename)
        assert img is not None, "Failed to load %s" % filename
        _FRAME_CACHE[name] = img
    return img


def auto_selftest_identity():
    r"""
    >>> "Spinal Tap"
    'Spinal Tap'
    >>> u"Spinal Tap"
    u'Spinal Tap'
    >>> "Spın̈al Tap"
    'Sp\xc4\xb1n\xcc\x88al Tap'
    >>> u"Spın̈al Tap"
    u'Sp\xc4\xb1n\xcc\x88al Tap'
    >>> print "Spinal Tap"
    Spinal Tap
    >>> print u"Spinal Tap"
    Spinal Tap
    >>> print "Spın̈al Tap"
    Spın̈al Tap
    >>> print u"Spın̈al Tap"  # doctest: +SKIP
    Sp\xc4\xb1n\xcc\x88al Tap
    >>> raise Exception("Spinal Tap")
    Traceback (most recent call last):
    Exception: Spinal Tap
    >>> raise Exception(u"Spinal Tap")
    Traceback (most recent call last):
    Exception: Spinal Tap
    >>> raise Exception("Spın̈al Tap")
    Traceback (most recent call last):
    Exception: Spın̈al Tap
    >>> raise Exception(u"Spın̈al Tap")
    Traceback (most recent call last):
    Exception: Sp\xc4\xb1n\xcc\x88al Tap
    """
    pass


def auto_selftest_print_something_unicode():
    r"""
    >>> print_something_unicode(0)
    Spinal Tap
    >>> print_something_unicode(1)
    Spinal Tap
    >>> print_something_unicode(2)
    Spın̈al Tap
    >>> print_something_unicode(3)  # doctest: +SKIP
    Sp\u0131n\u0308al Tap
    """
    pass


def auto_selftest_return_something_unicode():
    r"""
    >>> return_something_unicode(0)
    'Spinal Tap'
    >>> return_something_unicode(1)
    u'Spinal Tap'
    >>> return_something_unicode(2)
    'Sp\xc4\xb1n\xcc\x88al Tap'
    >>> return_something_unicode(3)
    u'Sp\u0131n\u0308al Tap'
    >>> print return_something_unicode(0)
    Spinal Tap
    >>> print return_something_unicode(1)
    Spinal Tap
    >>> print return_something_unicode(2)
    Spın̈al Tap
    >>> print return_something_unicode(3)  # doctest: +SKIP
    Sp\u0131n\u0308al Tap
    """
    pass
