# Docker container running Fedora for building & testing stb-tester RPMs on
# Fedora.

FROM fedora:23
MAINTAINER David Röthlisberger "david@rothlis.net"

# Build essentials:
RUN dnf install -y \
    copr-cli "dnf-command(builddep)" gcc git make rpm-build sudo wget

# Stb-tester build dependencies for building binary RPM:
RUN dnf install -y @BUILDREQUIRES@

RUN adduser stb-tester && \
    echo  "stb-tester	ALL=(ALL)	NOPASSWD: ALL" >>/etc/sudoers && \
    sed -i 's/Defaults.*requiretty//' /etc/sudoers

USER stb-tester
ENV HOME /home/stb-tester
WORKDIR /home/stb-tester
