# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration file to provision a Linux VM (run `vagrant up` from
# this directory) so that I can run Docker on my Mac to build packages for
# various versions of Fedora. (boot2docker doesn't suit my purposes because it
# doesn't allow shared volumes between the Mac host and the Linux container;
# the Vagrantfile in stb-tester/extra/vm is too heavyweight--it installs a GUI
# environment and thus takes ~15 minutes to provision.)
#
# For a reference of the config file options, see the online documentation at
# vagrantup.com.

Vagrant.configure("2") do |config|

  config.vm.box = "trusty64"  # Ubuntu 14.04LTS, 64 bit
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provision :shell, :path => "vagrant.sh"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../../", "/home/vagrant/stb-tester"

end
