name: ubuntu2204

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  make_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make ci-docker-images
    - name: Create and start CI container
      run: |
        docker container create \
          --name stb-tester-ci \
          --volume ${{ github.workspace }}:/project \
          --workdir /project \
          --tty \
          --env LANG=en_GB.UTF-8 \
          --env SHELL=/bin/bash \
          --env TERM=xterm \
          stbtester/ci:ubuntu2204 \
          cat \
        && docker container start stb-tester-ci
    - run: docker container exec stb-tester-ci git config --global --add safe.directory /project
    - run: docker container exec stb-tester-ci tesseract --version
    - run: docker container exec stb-tester-ci make check-pylint
    - run: docker container exec stb-tester-ci pyright --version
    - run: docker container exec stb-tester-ci make check-pyright
    - run: docker container exec stb-tester-ci make check-pytest
    - run: docker container exec stb-tester-ci make check-integrationtests
    - name: Stop and remove CI container
      run: |
        docker container stop stb-tester-ci \
        && docker container rm stb-tester-ci
      if: always()
